services:
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: always
  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    restart: unless-stopped

  # app:
  #   build: .
  #   container_name: mynotes_app
  #   ports:
  #     - "3001:3000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - chroma
  #     # - ollama
  #   volumes:
  #     - ./data:/app/data
  #   restart: unless-stopped
# volumes:
#   ollama_data: